version: "3.9"
services:
  webapp:                                                                                                                                                                                                                                                                                  
    container_name: backend 
    restart: always 
    build: . 
    ports:
      - "5432:5432"  
    links:
      - mongo 
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "4000:27017"